const clientEnv = {
  NEXT_PUBLIC_SANITY_PROJECT_ID:
    process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || '',
  NEXT_PUBLIC_SANITY_DATASET: process.env.NEXT_PUBLIC_SANITY_DATASET || '',
  NEXT_PUBLIC_SANITY_API_VERSION:
    process.env.NEXT_PUBLIC_SANITY_API_VERSION || '2026-02-27',
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL || '',
  NEXT_PUBLIC_SANITY_STUDIO_URL:
    process.env.NEXT_PUBLIC_SANITY_STUDIO_URL || '',
} as const;

export { clientEnv };
